version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: sav_postgres
    environment:
      POSTGRES_DB: sav_db
      POSTGRES_USER: sav_user
      POSTGRES_PASSWORD: sav_pass
    ports:
      - "5433:5432"
    volumes:
      - sav_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sav_user -d sav_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  sav_pgdata:
